"""Port of crates/vag-data/src/glyphs.rs `TableAlphabet::for_key`.

VCDS enciphers every `.rod` table's numeric/letter glyphs with a per-table
substitution generated by seeding the C runtime's `rand()` with the table id and
Fisher-Yates-shuffling both plaintext alphabets from that one stream (letters
first, digits second — they share the stream). This is a faithful port, verified
against the shipped Rust test vector (table 531 -> separator ',', digit order
`0.-8321574...`, `.-0238` -> 120543).

The point of re-porting it in Python is to audit the decode independently of the
Rust code, on STRUC/MUX/TTDOP specifically, which the Rust tests do not cover.
"""

PLAIN_LETTERS = list(b"abcdefghijklmnopqrstuvwxyz")
PLAIN_DIGITS  = list(b"0123456789,.-_")
SEPARATOR_SLOT = 10  # the comma: PLAIN_DIGITS[10]


class CrtRand:
    """Microsoft C runtime rand()/srand(), statically linked in VCDS."""
    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF
    def next(self):
        self.s = (self.s * 0x343FD + 0x269EC3) & 0xFFFFFFFF
        return (self.s >> 16) & 0x7FFF


class TableAlphabet:
    def __init__(self, key):
        r = CrtRand(key)
        letters = PLAIN_LETTERS[:]
        digits = PLAIN_DIGITS[:]
        for i in range(len(letters)):
            j = r.next() % len(letters)
            letters[i], letters[j] = letters[j], letters[i]
        for i in range(len(digits)):
            j = r.next() % len(digits)
            digits[i], digits[j] = digits[j], digits[i]
        self.letters = letters
        self.digits = digits
        self.dig_pos = {chr(g): i for i, g in enumerate(digits)}
        self.let_pos = {chr(g): i for i, g in enumerate(letters)}

    def separator(self):
        return chr(self.digits[SEPARATOR_SLOT])

    def decode(self, field):
        """Cipher glyphs -> plaintext glyphs (digits keep '.' '-' '_', letters
        keep case). None if any glyph is in neither alphabet."""
        out = []
        for ch in field:
            low = ch.lower()
            if low in self.dig_pos:
                out.append(chr(PLAIN_DIGITS[self.dig_pos[low]]))
            elif low in self.let_pos:
                p = chr(PLAIN_LETTERS[self.let_pos[low]])
                out.append(p.upper() if ch.isupper() else p)
            else:
                return None
        return ''.join(out) if out else None


def selftest():
    a = TableAlphabet(531)
    assert a.separator() == ','
    assert a.decode(".-0238") == "120543"
    assert a.decode(".0374730") == "10489840"
    print("glyphs selftest OK (table 531)")


if __name__ == "__main__":
    selftest()
